/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package protocols.fridge;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public interface Fridge {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"Fridge\",\"namespace\":\"protocols.fridge\",\"types\":[],\"messages\":{}}");

  @SuppressWarnings("all")
  public interface Callback extends Fridge {
    public static final org.apache.avro.Protocol PROTOCOL = protocols.fridge.Fridge.PROTOCOL;
  }
}