/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package protocols.fridge;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public interface Fridge {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"Fridge\",\"namespace\":\"protocols.fridge\",\"types\":[{\"type\":\"error\",\"name\":\"Failure\",\"doc\":\"Failure\",\"fields\":[{\"name\":\"info\",\"type\":\"string\"}]}],\"messages\":{\"ping\":{\"request\":[],\"response\":\"boolean\"},\"getItems\":{\"request\":[],\"response\":{\"type\":\"array\",\"items\":\"string\"},\"errors\":[\"Failure\"]},\"removeItem\":{\"request\":[{\"name\":\"item\",\"type\":\"string\"}],\"response\":\"null\",\"errors\":[\"Failure\"]},\"addItem\":{\"request\":[{\"name\":\"item\",\"type\":\"string\"}],\"response\":\"null\",\"errors\":[\"Failure\"]}}}");
  /**
   */
  boolean ping() throws org.apache.avro.AvroRemoteException;
  /**
   */
  java.util.List<java.lang.CharSequence> getItems() throws org.apache.avro.AvroRemoteException, protocols.fridge.Failure;
  /**
   */
  java.lang.Void removeItem(java.lang.CharSequence item) throws org.apache.avro.AvroRemoteException, protocols.fridge.Failure;
  /**
   */
  java.lang.Void addItem(java.lang.CharSequence item) throws org.apache.avro.AvroRemoteException, protocols.fridge.Failure;

  @SuppressWarnings("all")
  public interface Callback extends Fridge {
    public static final org.apache.avro.Protocol PROTOCOL = protocols.fridge.Fridge.PROTOCOL;
    /**
     * @throws java.io.IOException The async call could not be completed.
     */
    void ping(org.apache.avro.ipc.Callback<java.lang.Boolean> callback) throws java.io.IOException;
    /**
     * @throws java.io.IOException The async call could not be completed.
     */
    void getItems(org.apache.avro.ipc.Callback<java.util.List<java.lang.CharSequence>> callback) throws java.io.IOException;
    /**
     * @throws java.io.IOException The async call could not be completed.
     */
    void removeItem(java.lang.CharSequence item, org.apache.avro.ipc.Callback<java.lang.Void> callback) throws java.io.IOException;
    /**
     * @throws java.io.IOException The async call could not be completed.
     */
    void addItem(java.lang.CharSequence item, org.apache.avro.ipc.Callback<java.lang.Void> callback) throws java.io.IOException;
  }
}