/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package protocols.user;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public interface User {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"User\",\"namespace\":\"protocols.user\",\"types\":[],\"messages\":{\"inHouse\":{\"request\":[],\"response\":\"boolean\"},\"message\":{\"doc\":\"Send a message t\",\"request\":[{\"name\":\"contents\",\"type\":\"string\"}],\"response\":\"null\"}}}");
  /**
   */
  boolean inHouse() throws org.apache.avro.AvroRemoteException;
  /**
   * Send a message t
   */
  java.lang.Void message(java.lang.CharSequence contents) throws org.apache.avro.AvroRemoteException;

  @SuppressWarnings("all")
  public interface Callback extends User {
    public static final org.apache.avro.Protocol PROTOCOL = protocols.user.User.PROTOCOL;
    /**
     * @throws java.io.IOException The async call could not be completed.
     */
    void inHouse(org.apache.avro.ipc.Callback<java.lang.Boolean> callback) throws java.io.IOException;
    /**
     * Send a message t
     * @throws java.io.IOException The async call could not be completed.
     */
    void message(java.lang.CharSequence contents, org.apache.avro.ipc.Callback<java.lang.Void> callback) throws java.io.IOException;
  }
}