/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package protocols.controller;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public interface Controller {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"Controller\",\"namespace\":\"protocols.controller\",\"types\":[],\"messages\":{}}");

  @SuppressWarnings("all")
  public interface Callback extends Controller {
    public static final org.apache.avro.Protocol PROTOCOL = protocols.controller.Controller.PROTOCOL;
  }
}