/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package protocols.replication;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
/** Temperature measured by a sensor */
@org.apache.avro.specific.AvroGenerated
public class TemperatureHistory extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -3112092764255108869L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"TemperatureHistory\",\"namespace\":\"protocols.replication\",\"doc\":\"Temperature measured by a sensor\",\"fields\":[{\"name\":\"id\",\"type\":\"int\"},{\"name\":\"temperatures\",\"type\":{\"type\":\"array\",\"items\":\"double\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<TemperatureHistory> ENCODER =
      new BinaryMessageEncoder<TemperatureHistory>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<TemperatureHistory> DECODER =
      new BinaryMessageDecoder<TemperatureHistory>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<TemperatureHistory> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<TemperatureHistory> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<TemperatureHistory>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this TemperatureHistory to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a TemperatureHistory from a ByteBuffer. */
  public static TemperatureHistory fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public int id;
  @Deprecated public java.util.List<java.lang.Double> temperatures;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public TemperatureHistory() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param temperatures The new value for temperatures
   */
  public TemperatureHistory(java.lang.Integer id, java.util.List<java.lang.Double> temperatures) {
    this.id = id;
    this.temperatures = temperatures;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return temperatures;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.Integer)value$; break;
    case 1: temperatures = (java.util.List<java.lang.Double>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public java.lang.Integer getId() {
    return id;
  }

  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.Integer value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'temperatures' field.
   * @return The value of the 'temperatures' field.
   */
  public java.util.List<java.lang.Double> getTemperatures() {
    return temperatures;
  }

  /**
   * Sets the value of the 'temperatures' field.
   * @param value the value to set.
   */
  public void setTemperatures(java.util.List<java.lang.Double> value) {
    this.temperatures = value;
  }

  /**
   * Creates a new TemperatureHistory RecordBuilder.
   * @return A new TemperatureHistory RecordBuilder
   */
  public static protocols.replication.TemperatureHistory.Builder newBuilder() {
    return new protocols.replication.TemperatureHistory.Builder();
  }

  /**
   * Creates a new TemperatureHistory RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new TemperatureHistory RecordBuilder
   */
  public static protocols.replication.TemperatureHistory.Builder newBuilder(protocols.replication.TemperatureHistory.Builder other) {
    return new protocols.replication.TemperatureHistory.Builder(other);
  }

  /**
   * Creates a new TemperatureHistory RecordBuilder by copying an existing TemperatureHistory instance.
   * @param other The existing instance to copy.
   * @return A new TemperatureHistory RecordBuilder
   */
  public static protocols.replication.TemperatureHistory.Builder newBuilder(protocols.replication.TemperatureHistory other) {
    return new protocols.replication.TemperatureHistory.Builder(other);
  }

  /**
   * RecordBuilder for TemperatureHistory instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<TemperatureHistory>
    implements org.apache.avro.data.RecordBuilder<TemperatureHistory> {

    private int id;
    private java.util.List<java.lang.Double> temperatures;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(protocols.replication.TemperatureHistory.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.temperatures)) {
        this.temperatures = data().deepCopy(fields()[1].schema(), other.temperatures);
        fieldSetFlags()[1] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing TemperatureHistory instance
     * @param other The existing instance to copy.
     */
    private Builder(protocols.replication.TemperatureHistory other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.temperatures)) {
        this.temperatures = data().deepCopy(fields()[1].schema(), other.temperatures);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public java.lang.Integer getId() {
      return id;
    }

    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public protocols.replication.TemperatureHistory.Builder setId(int value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public protocols.replication.TemperatureHistory.Builder clearId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'temperatures' field.
      * @return The value.
      */
    public java.util.List<java.lang.Double> getTemperatures() {
      return temperatures;
    }

    /**
      * Sets the value of the 'temperatures' field.
      * @param value The value of 'temperatures'.
      * @return This builder.
      */
    public protocols.replication.TemperatureHistory.Builder setTemperatures(java.util.List<java.lang.Double> value) {
      validate(fields()[1], value);
      this.temperatures = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'temperatures' field has been set.
      * @return True if the 'temperatures' field has been set, false otherwise.
      */
    public boolean hasTemperatures() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'temperatures' field.
      * @return This builder.
      */
    public protocols.replication.TemperatureHistory.Builder clearTemperatures() {
      temperatures = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public TemperatureHistory build() {
      try {
        TemperatureHistory record = new TemperatureHistory();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.Integer) defaultValue(fields()[0]);
        record.temperatures = fieldSetFlags()[1] ? this.temperatures : (java.util.List<java.lang.Double>) defaultValue(fields()[1]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<TemperatureHistory>
    WRITER$ = (org.apache.avro.io.DatumWriter<TemperatureHistory>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<TemperatureHistory>
    READER$ = (org.apache.avro.io.DatumReader<TemperatureHistory>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
