/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package protocols.light;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public interface Light {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"Light\",\"namespace\":\"protocols.light\",\"types\":[],\"messages\":{\"powerOn\":{\"request\":[],\"response\":\"boolean\"},\"powerOff\":{\"request\":[],\"response\":\"boolean\"},\"getStatus\":{\"request\":[],\"response\":\"boolean\"},\"ping\":{\"request\":[],\"response\":\"boolean\"},\"reRegister\":{\"doc\":\"When a controller goes down, the new controller calls this method to let the devices know ther is a new controller\",\"request\":[{\"name\":\"ipadress\",\"type\":\"string\"},{\"name\":\"port\",\"type\":\"int\"}],\"response\":\"null\"}}}");
  /**
   */
  boolean powerOn() throws org.apache.avro.AvroRemoteException;
  /**
   */
  boolean powerOff() throws org.apache.avro.AvroRemoteException;
  /**
   */
  boolean getStatus() throws org.apache.avro.AvroRemoteException;
  /**
   */
  boolean ping() throws org.apache.avro.AvroRemoteException;
  /**
   * When a controller goes down, the new controller calls this method to let the devices know ther is a new controller
   */
  java.lang.Void reRegister(java.lang.CharSequence ipadress, int port) throws org.apache.avro.AvroRemoteException;

  @SuppressWarnings("all")
  public interface Callback extends Light {
    public static final org.apache.avro.Protocol PROTOCOL = protocols.light.Light.PROTOCOL;
    /**
     * @throws java.io.IOException The async call could not be completed.
     */
    void powerOn(org.apache.avro.ipc.Callback<java.lang.Boolean> callback) throws java.io.IOException;
    /**
     * @throws java.io.IOException The async call could not be completed.
     */
    void powerOff(org.apache.avro.ipc.Callback<java.lang.Boolean> callback) throws java.io.IOException;
    /**
     * @throws java.io.IOException The async call could not be completed.
     */
    void getStatus(org.apache.avro.ipc.Callback<java.lang.Boolean> callback) throws java.io.IOException;
    /**
     * @throws java.io.IOException The async call could not be completed.
     */
    void ping(org.apache.avro.ipc.Callback<java.lang.Boolean> callback) throws java.io.IOException;
    /**
     * When a controller goes down, the new controller calls this method to let the devices know ther is a new controller
     * @throws java.io.IOException The async call could not be completed.
     */
    void reRegister(java.lang.CharSequence ipadress, int port, org.apache.avro.ipc.Callback<java.lang.Void> callback) throws java.io.IOException;
  }
}